<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body { font-family: Arial, sans-serif; }
        .header { text-align: center; margin-bottom: 30px; }
        .report-info { margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f4f4f4; }
        .footer { text-align: center; font-size: 12px; margin-top: 30px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <p>Generated on {{ now()->format('F d, Y') }}</p>
    </div>

    <div class="report-info">
        <p>Period: {{ \Carbon\Carbon::parse($params['start_date'])->format('M d, Y') }} - {{ \Carbon\Carbon::parse($params['end_date'])->format('M d, Y') }}</p>
        <p>Total Records: {{ $data->count() }}</p>
    </div>

    @if($data->isNotEmpty())
        <table>
            <thead>
                <tr>
                    @foreach(array_keys($data->first()) as $header)
                        <th>{{ $header }}</th>
                    @endforeach
                </tr>
            </thead>
            <tbody>
                @foreach($data as $row)
                    <tr>
                        @foreach($row as $value)
                            <td>{{ $value }}</td>
                        @endforeach
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <p>No data available for this period.</p>
    @endif

    <div class="footer">
        <p>Generated by VetCare System</p>
    </div>
</body>
</html>
